main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('departments/', views.departments, name='departments'),
    path('department/<str:pk>/', views.department, name='department'),
    path('programmes/', views.programmes, name='programmes'),
    path('programme/<str:pk>/', views.programme, name='programme'),
    path('latest_updates/', views.latest_updates, name='latest_updates'),
    path('latest_update/<str:pk>/', views.latest_update, name='latest_update'),
    path('notices/', views.notices, name='notices'),
    path('notice/<str:pk>/', views.notice, name='notice'),
    path('acadcalendar_fees_contact/', views.acadcalendar_fees_contact,
         name='acadcalendar_fees_contact'),
    path('trades/',
         views.trades, name='trades'),
    path('trade_images/<str:pk>/',
         views.trade_images, name='trade_images'),
    path('add_department/',
         views.add_department, name='add_department'),
    path('add_academic_calendar/',
         views.add_academic_calendar, name='add_academic_calendar'),
    path('add_fees/',
         views.add_fees, name='add_fees'),
    path('add_contact/',
         views.add_contact, name='add_contact'),
    path('add_institution/',
         views.add_institution, name='add_institution'),
    path('add_latest_update/',
         views.add_latest_update, name='add_latest_update'),
    path('add_notice/',
         views.add_notice, name='add_notice'),
    path('add_programme/',
         views.add_programme, name='add_programme'),
    path('add_trade_image/',
         views.add_trade_image, name='add_trade_image'),
    path('add_trade/',
         views.add_trade, name='add_trade'),
    path('update_trade/<str:pk>/',
         views.update_trade, name='update_trade'),
    path('update_trade_image/<str:pk>/',
         views.update_trade_image, name='update_trade_image'),
    path('update_department/<str:pk>/',
         views.update_department, name='update_department'),
    path('update_academic_calendar/<str:pk>/',
         views.update_academic_calendar, name='update_academic_calendar'),
    path('update_fees/<str:pk>/',
         views.update_fees, name='update_fees'),
    path('update_contact/<str:pk>/',
         views.update_contact, name='update_contact'),
    path('update_institution/<str:pk>/',
         views.update_institution, name='update_institution'),
    path('update_latest_update/<str:pk>/',
         views.update_latest_update, name='update_latest_update'),
    path('update_notice/<str:pk>/',
         views.update_notice, name='update_notice'),
    path('update_programme/<str:pk>/',
         views.update_programme, name='update_programme'),
    path('login_user/',
         views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('delete_department/<str:pk>/',
         views.delete_department, name='delete_department'),
    path('delete_programme/<str:pk>/',
         views.delete_programme, name='delete_programme'),
    path('delete_latest_update/<str:pk>/',
         views.delete_latest_update, name='delete_latest_update'),
    path('delete_notice/<str:pk>/',
         views.delete_notice, name='delete_notice'),
    path('delete_trade/<str:pk>/',
         views.delete_trade, name='delete_trade'),
]

moramora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

handler404 = 'main.views.handler404'

# sets the path for users to upload pictures to a directory
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Institution(models.Model):
    """
    This stores information about the college
    """
    inst_name = models.CharField(max_length=255)
    about = RichTextField(max_length=700)
    img = models.ImageField(upload_to='inst/', default='default.png')
    vision = RichTextField(max_length=350)
    mission = RichTextField(max_length=350)
    is_active = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.inst_name

    class Meta:
        ordering = ['-created']


class Contact(models.Model):
    """
    This stores information about the contact person for the college
    """
    inst = models.ForeignKey(Institution, on_delete=models.CASCADE)
    contact_person = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    postal_address = models.CharField(max_length=255)
    email = models.EmailField(default='youremail@example.com', max_length=255)
    landline = models.IntegerField()
    digicel = models.IntegerField()
    telikom = models.IntegerField()
    vodaphone = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.contact_person

    class Meta:
        ordering = ['-created']


class PngNqf(models.Model):
    """ 
    This lists all the levels of PNG National Qualification Framework
    """
    nqf_level = models.CharField(max_length=10)
    qualification = models.CharField(max_length=255)

    def __str__(self):
        return self.qualification

    class Meta:
        verbose_name = 'PNG NQF'


class Department(models.Model):
    """ 
    This stores information about the respective departments in the college
    """
    dept = models.CharField(
        max_length=255, default='Department of ', unique=True)
    desc = RichTextField(max_length=1500)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.dept


class Programme(models.Model):
    """ 
    This stores information on the programmes offered by the college
    """
    dept = models.ForeignKey(Department, on_delete=models.CASCADE)
    inst = models.ForeignKey(Institution, on_delete=models.CASCADE)
    prog_name = models.CharField(
        max_length=255, default='National Certificate in ', unique=True)
    nqf = models.ForeignKey(PngNqf, on_delete=models.CASCADE)
    prog_code = models.CharField(max_length=10, unique=True)
    prog_duration = models.IntegerField()
    prog_quota = models.IntegerField()
    prog_description = RichTextField(max_length=2500)
    prog_requirement = RichTextField(
        max_length=1000, default='LL grade greate than B')
    is_active = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.prog_name

    class Meta:
        ordering = ['-prog_name']


class Notice(models.Model):
    """ 
    This provides a space for the college to post Notices for the students and public
    This is based on programmes
    """
    prog = models.ForeignKey(Programme, on_delete=models.CASCADE)
    title = models.CharField(max_length=700, unique=True)
    intro = RichTextField(max_length=700)
    img = models.ImageField(null=True, blank=True,
                            upload_to='notices/', unique=True)
    main_body = RichTextField(max_length=5000)
    outro = RichTextField(max_length=700)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']


class LatestUpdate(models.Model):
    """ 
    Provides the latest news/update/development in the college
    """
    inst = models.ForeignKey(Institution, on_delete=models.CASCADE)
    title = models.CharField(max_length=700, unique=True)
    intro = RichTextField(max_length=700)
    img = models.ImageField(null=True, blank=True,
                            upload_to='updates/', default="default.png", unique=True)
    main_body = RichTextField(max_length=5000)
    outro = RichTextField(max_length=700)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']


class FeeStructure(models.Model):
    """ 
    This section provides/stores information on the fee structure of the college
    """
    year = models.IntegerField(unique=True)
    desc = RichTextField(max_length=700)
    hecas_resid = models.FloatField()
    hecas_non_resid = models.FloatField()
    ss_resid = models.FloatField()
    ss_non_resid = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return (f"Fee Structure for the year {self.year}")

    class Meta:
        ordering = ['-created']


class AcademicCalendar(models.Model):
    """
    This section will store information on the academic calendar of the college
    """
    year = models.IntegerField()
    note = RichTextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    sem_one_reg_begins = models.DateField()
    sem_one_reg_ends = models.DateField()
    sem_one_cls_begins = models.DateField()
    sem_one_cls_ends = models.DateField()
    sem_one_brk_begins = models.DateField()
    sem_one_brk_ends = models.DateField()
    sem_two_reg_begins = models.DateField()
    sem_two_reg_ends = models.DateField()
    sem_two_cls_begins = models.DateField()
    sem_two_cls_ends = models.DateField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return (f"Academic Calendar for the year {self.year}")

    class Meta:
        ordering = ['-created']


class Trade(models.Model):
    trade = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.trade


class ImageLibrary(models.Model):
    """
    This will stores images of the college
    """
    trade = models.ForeignKey(Trade, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    img = models.ImageField(upload_to='img_lib/',
                            default='default.png', unique=True)
    desc = models.CharField(max_length=400)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']

main/templates/main/acadcalendar_fees_contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Calendar
{% endblock title %}
{% block content %}
<div class="container border">
    <br>
    <div class="row justify-content-center">
        <div class="container text-center m-auto">
            <img src="{% static 'images/logo.png' %}" alt="logo">
        </div>
        <p class="display-4 text-center">Our Academic Calendar ({{acad_cal.year}})</p>
        {% if acad_cal %}
            <div class="text-center">
                {% if request.user.is_authenticated %}
                    <span>
                        <a href="{% url 'update_academic_calendar' acad_cal.id %}" class=" m-3 rounded-pill btn btn-secondary"><i
                                class="fa-regular fa-pen-to-square"></i> Update</a>
                    </span>
                {% endif %}
            </div>
            {% if acad_cal.is_active %}
                <table class="table table-striped w-75" style="color: #145A32">
                    <tr>
                        <th>Activity</th>
                        <th>Starting Date</th>
                        <th>Ending Date</th>
                    </tr>
                    <tr>
                        <td>Semester One Registration</td>
                        <td>{{acad_cal.sem_one_reg_begins}}</td>
                        <td>{{acad_cal.sem_one_reg_ends}} </td>
                    </tr>
                    <tr>
                        <td>Semester One Classes</td>
                        <td>{{acad_cal.sem_one_cls_begins}} </td>
                        <td>{{acad_cal.sem_one_cls_ends}} </td>
                    </tr>
                    <tr>
                        <td>Semester One Break</td>
                        <td>{{acad_cal.sem_one_brk_begins}} </td>
                        <td>{{acad_cal.sem_one_brk_ends}} </td>
                    </tr>
                    <tr>
                        <td>Semester Two Registration</td>
                        <td>{{acad_cal.sem_two_reg_begins}}</td>
                        <td>{{acad_cal.sem_two_reg_ends}} </td>
                    </tr>
                    <tr>
                        <td>Semester Two Classes</td>
                        <td>{{acad_cal.sem_two_cls_begins}}</td>
                        <td>{{acad_cal.sem_two_cls_ends}} </td>
                    </tr>
                </table>
            {% endif %}
        {% else %}
            <p class="text-center"><i>No information to display</i></p>
        {% endif %}
    </div>
    <br>

    <div class="row justify-content-center">
        <p class="display-4 text-center" >Our Fees Structure for ({{fee.year}})</p>
        {% if fee %}
        <div class="text-center">
            {% if request.user.is_authenticated %}
            <span>
                <a href="{% url 'update_fees' fee.id %} class=" class="m-3 rounded-pill btn btn-secondary"><i
                                class="fa-regular fa-pen-to-square"></i> Update</a>
            </span>
            {% endif %}
        </div>
            {% if fee.is_active %}
                <table class="table table-striped w-75" style="color: #145A32">
                    <tr>
                        <th>Student Type</th>
                        <th>Amount</th>
                    </tr>
                    <tr>
                        <td>HECAS Residence</td>
                        <td>K{{fee.hecas_resid|floatformat:2}}</td>
                    </tr>
                    <tr>
                        <td>HECAS Non-Residence</td>
                        <td>K{{fee.hecas_non_resid|floatformat:2}}</td>
                    </tr>
                    <tr>
                        <td>Self-Sponsor Residence</td>
                        <td>K{{fee.ss_resid|floatformat:2}}</td>
                    </tr>
                    <tr>
                        <td>Self-Sponsor Non-Residence</td>
                        <td>K{{fee.ss_non_resid|floatformat:2}}</td>
                    </tr>
                </table>
            {% endif %}
        {% else %}
                <p class="text-center"><i>No information to display</i></p>
        {% endif %}
    </div>
    <br>

    <div class="row justify-content-center">
        <p class="display-4 text-center">Our Contacts</p>
        
        {% if contacts %}
            {% for contact in contacts %}
                <div id="background" class="col-lg-5 rounded border m-3 p-3">
                    {% if request.user.is_authenticated %}
                        <span class="fs-3"><a href="{% url 'update_contact' contact.id %}">{{contact.contact_person}}</a></span><br>
                    {% else %}
                        <span class="fs-3">{{contact.contact_person}}</span><br>
                    {% endif %}
                    <span>{{contact.designation}}</span><br>
                    <span>{{contact.postal_address}}</span><br>
                    <span>{{contact.email}}</span><br>
                    <span>{{contact.digicel}}, {{contact.telikom}}, {{contact.vodaphone}}</span><br>
                </div>
            {% endfor %}
        {% else %}
            <p class='text-center'><i>No information to display</i></p>
        {% endif %} 
    </div>
    <br>
</div>
{% endblock content %}

main/templates/main/delete.html
{% extends 'base.html' %}
{% block content %}
    <div id="background" class="container text-center my-5 py-5">
        <form action="" method="POST">
            {% csrf_token %}
            <p class="fs-4">Are you sure you want to delete <u><b>{{object}}</b></u>?</p>
            <input class="btn btn-primary mx-1" type="submit" value="Yes">
            <a class="btn btn-outline-secondary mx-1" href="{% url 'home' %}">Back</a>
        </form>
    </div>
{% endblock content %}

main/templates/main/department.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ department.dept }}
{% endblock title %}
{% block content %}
<div class="container border">
    <br>
    <div class="container">
        <div class="container text-center m-auto">
            <img src="{% static 'images/logo.png' %}" alt="logo">
        </div>
        <br>
        <div id="background" class="container fw-bold">
            <span>
                <p class="display-4">{{department.dept|safe}}</p>
                {% if request.user.is_authenticated %}
                <div><a href="{% url 'update_department' department.id %}" class="card-link"><i class="fa-regular fa-pen-to-square"></i>
                Update</a></div>
                {% endif %}
            </span>
            <hr>
        </div>
        <div class="container">
            <p class="fs-2">About the Department</p>
            <p>{{department.desc|safe}}</p>
        </div>
        <div class="container">
            <p class="fs-2">
                Programmes we offer:
            </p>
            <!-- check if this department have any programmes -->
            {% if department.programme_set.all %}
                <!-- if there is any, it loops through to display them -->
                {% for programme in department.programme_set.all %}
                    <span class="fs-5">
                        <a class="text-decoration-none" href="{% url 'programme' programme.id %}">{{programme.prog_name}}</a><br>
                    </span>
                {% endfor %}
            {% else %}
                    <!-- if there is no programme it displays this message -->
                <p><i>No programmes to display at the moment</i></p>
            {% endif %}
        </div>
    </div>
    <div>
        <a class="btn btn-primary" href="{% url 'departments' %}">Back</a>
    </div>
    <br>
</div>
{% endblock content %}

main/templates/main/error_handling.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md text-center">
            <p class="display-1">404: Page Not Found</p>
        </div>
    </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container border">
    <main>
        <div class="background row text-center p-5">
            <img class="m-auto" style="width: 20rem; border-radius: 50%;" src="{% static 'images/logo.png' %}" alt="logo">
            <div>
                {% if request.user.is_authenticated %}
                    {% if institution %}
                    <span>
                        <a href="{% url 'update_institution' institution.id %}" class=" m-3 rounded-pill btn btn-light"><i class="fa-regular fa-pen-to-square"></i> Update</a>
                    </span>
                    {% endif %}
                {% endif %}
            </div>
            <h1 class="fs-1">Welcome to</h1>
            {% if institution.inst_name %}
                <p class="display-1 fw-bold m-auto py-4">{{ institution.inst_name|safe }}</p>
            {% else %}
                <p><i>No information to display</i></p>
            {% endif %}
            <h1 class="fs-1">website</h1>
        </div>
        <div class="row">
            <div class="col-lg-6 align-item-center text-center py-5">
                <h1 class="fs-1">About Us</h1>
                {% if institution.about %}
                    <p class="fs-5">{{institution.about|safe}}</p>
                {% else %}
                    <p><i>No information to display</i></p>
                {% endif %}
            </div>
            <div class="col-lg-6 py-5 m-auto">
                {% if institution.img.url %}
                    <img class="img-fluid rounded" src="{{ institution.img.url }}" alt="a picture">
                {% else %}
                    <p><i>No image to display</i></p>
                {% endif %}
            </div>
        </div>
        <div class="col">
            <div class="background row text-center p-5">
                <h1 class="fs-1">Our Vision</h1>
                {% if institution.vision %}
                    <p class="fs-5">{{institution.vision|safe}}</p>
                {% else %}
                    <p><i>No vision to display</i></p>
                {% endif %}
            </div>
            <div class="row text-center p-5">
                <h1 class="fs-1">Our Mission</h1>
                {% if institution.mission %}
                    <p class="fs-5">{{institution.mission|safe}}</p>
                {% else %}
                    <p><i>No mission to display</i></p>
                {% endif %}
            </div>
        </div>
        <div class="row justify-content-around">
            <div id="background" class="col-md-3 border rounded text-center p-3 m-2">
                <a href="{% url 'latest_updates' %}" id="headings">
                    <h1 class="fs-2 m-auto">Read Updates</h1>
                </a>
            </div>
            <div id="background" class="col-md-3 border rounded text-center p-3 m-2">
                <a href="{% url 'notices' %}" id="headings">
                    <h1 class="fs-2 m-auto">Read Notices</h1>
                </a>
            </div>
            <div id="background" class="col-md-3 border rounded text-center p-3 m-2">
                <a href="{% url 'trades' %}" id="headings">
                    <h1 class="fs-2 m-auto">View Images</h1>
                </a>
            </div>
        </div>
    </main>
</div>
{% endblock content %}

main/templates/main/image_library.html
{% extends 'base.html' %}
{% block content %}
<div class="container border">
    <br>
    <h1 class="display-1" id="headings">{{trade_images.trade}}</h1>
    <div class="row">
        {% for trade_image in trade_images %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{image.img}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{trade_image.title}}</h5>
                <p class="card-text">{{trade_image.desc}}</p>
                <a href="#" class="btn btn-primary">Back</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

main/templates/main/latest_update.html
{% extends 'base.html' %}
{% block title %}
    {{latest_update.title}}
{% endblock title %}
{% block content %}
    <div class="container border">
        <br>
        <div class="container">
            <div id="background" class="container fw-bold">
                <span>
                    <p class="display-6">{{latest_update.title|safe}} </span>
                <hr>
            </div>
            <div class="container">
                <p>{{latest_update.intro|safe}}</p>
                {% if latest_update.img.url is not None %}
                    <img class="img-fluid" style="width: 40em;" src="{{latest_update.img.url}}" alt="an image">
                    <br>
                {% else %}
                    <p>NO PICTURE TO DISPLAY</p>
                {% endif %}
                <br>
                <p>{{latest_update.main_body|safe}}</p>
                <p>{{latest_update.outro|safe}}</p>
            </div>
            <div class="container">
                <a class="btn btn-primary" href="{% url 'latest_updates' %}">Back</a>
            </div>
        </div>
        <br>
    </div>
{% endblock content %}

main/templates/main/latest_updates.html
{% extends 'base.html' %}
{% block title %}
    Latest Updates
{% endblock title %}
{% block content %}
<div class="container border">
    <br>
    <div class="container">
        <div class="row">
            <div class="row text-center">
                <h1 class="display-1">Our Latest Updates</h1>
                <p>Read the <u>LATEST UPDATES</u> to stay informed!!!</p>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        {% if user.is_authenticated %}
            {% if latest_updates %}
                {% for latest_update in latest_updates %}
                    <div class="card col-lg-5 border rounded">
                        {% if latest_update.is_active %}
                            <p><strong>Status:</strong> Active</p>
                        {% else %}
                            <p><strong>Status:</strong> Deactivated</p>
                        {% endif %}
                        <p class="fs-3">{{latest_update.title}}</p>
                        <p>{{latest_update.intro|safe|truncatewords:20}}</p>
                        <span><a class="btn btn-primary mx-1" href="{% url 'latest_update' latest_update.id %}"><i class="fa-regular fa-eye"></i> View</a></span>
                        <span><a class="btn btn-outline-secondary mx-1" href="{% url 'update_latest_update' latest_update.id %}"><i class="fa-regular fa-pen-to-square"></i> Update</a></span>
                        <span><a class="btn btn-outline-danger mx-1" href="{% url 'delete_latest_update' latest_update.id %}"><i class="fa-solid fa-trash"></i> Delete</a></span>
                    </div>
                {% endfor %}
            {% else %}
                <div class="text-center">
                    <p><i>No latest_updates to display the moment</i></p>
                </div>
            {% endif %}
        {% else %}
            {% for latest_update in latest_updates %}
                {% if latest_update.is_active %}
                    <div id="background" class="cards col-lg-5 border rounded">
                        <p class="fs-3">{{latest_update.title}}</p>
                        <p>{{latest_update.intro|safe|truncatewords:20}}</p>
                        <span><a class="btn btn-primary" href="{% url 'latest_update' latest_update.id %}">View</a></span>
                    </div>
                {% else %}
                    <div class="text-center">
                        <p><i>No departments to display the moment</i></p>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

main/templates/main/notice.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{notice.title}}
{% endblock title %}
{% block content %}
<div class="container border">
    <div class="container">
        <br>
        <div class="container">
            <img src="{% static 'images/logo.png' %}" alt="logo">
        </div>
        <div class="container">
            <div id="background" class="container fw-bold">
                <span>
                    <h1 class="display-5">{{notice.title}}</h1>
                </span>
                <span>Added on {{notice.created}} </span>
                <hr>
            </div>
            <div class="container">
                <p>{{notice.intro|safe}}</p>
                {% if notice.img.url is not None %}
                    <img class="img-fluid" style="width: 40em;" src="{{notice.img.url}}" alt="an image">
                    <br>
                {% endif %}
                <br>
                <p>{{notice.main_body|safe}}</p>
                <p>{{notice.outro|safe}}</p>
            </div>
            <div class="container">
                <a class="btn btn-primary" href="{% url 'notices' %}">Back</a>
            </div>
        </div>
        <br>
    </div>
</div>
{% endblock content %}

main/templates/main/notices.html
{% extends 'base.html' %}
{% block title %}
    Notices
{% endblock title %}
{% block content %}
<div class="container border">
    <br>
    <div class="container">
        <div class="row">
            <div class="row text-center">
                <h1 class="display-1">Our Notice Board</h1>
                <p>Read your <u>NOTICES</u> here to stay informed!!!</p>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        {% if user.is_authenticated %}
            {% if notices %}
                {% for notice in notices %}
                    <div id="background" class="col-lg-5 border rounded">
                        {% if notice.is_active %}
                            <p><strong>Status:</strong> Active</p>
                        {% else %}
                            <p><strong>Status:</strong> Deactivated</p>
                        {% endif %}
                        <p class="fs-3">{{notice.title}}</p>
                        <p>{{notice.intro|safe|truncatewords:20}}</p>
                        <span><a class="btn btn-primary mx-1" href="{% url 'notice' notice.id %}">View</a></span>
                        <span><a class="btn btn-outline-secondary mx-1" href="{% url 'update_notice' notice.id %}">Update</a></span>
                        <span><a class="btn btn-outline-danger mx-1" href="{% url 'delete_notice' notice.id %}"><i
                                    class="fa-solid fa-trash"></i> Delete</a></span>
                    </div>
                {% endfor %}
            {% else %}
                <div class="text-center">
                    <p><i>No notices to display the moment</i></p>
                </div>
            {% endif %}
        {% else %}
            {% for notice in notices %}
                {% if notice.is_active %}
                    <div class="cards col-lg-5 border rounded">
                        <p class="fs-3">{{notice.title}}</p>
                        <p>{{notice.intro|safe|truncatewords:20}}</p>
                        <span><a class="btn btn-primary" href="{% url 'notice' notice.id %}">View</a></span>
                    </div>
                {% else %}
                    <div class="text-center">
                        <p><i>No notices to display the moment</i></p>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

main/templates/main/programme.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{programme.prog_name}}
{% endblock title %}
{% block content %}
<div class="container border">
    <br>
    <div class="container">
        <div class="container text-center m-auto">
            <img src="{% static 'images/logo.png' %}" alt="logo">
        </div>
        <div class="container fw-bold">
            <span><p class="display-4">{{programme.prog_name|safe}}</p></span>
            <span>Code: {{programme.prog_code|safe}} | </span>
            <span>Duration: {{programme.prog_duration|safe}} year(s) | </span>
            <span>NQF Level: {{programme.nqf|safe}} | </span>
            <span>Qouta: {{programme.prog_quota|safe}} | </span>
            {% if request.user.is_authenticated %}
            <span><a href="{% url 'update_programme' programme.id %}" class="card-link"><i class="fa-regular fa-pen-to-square"></i>
            Update</a></span>
            {% endif %}
            <hr>
        </div>
        <div class="container">
            <p class="fs-1">Programme Description</p>
            <p>{{programme.prog_description|safe}}</p>
        </div>
        <div class="container">
            <p class="fs-1">Programme Requirements</p>
            <p>{{programme.prog_requirement|safe}}</p>
        </div>
    </div>
    <div>
        <a class="btn btn-primary" href="{% url 'programmes' %}">Back</a>
    </div>
    <br>
    
</div>
{% endblock content %}